### ISSUE TITLE
Feature Request: Update event to indicate actual status change 

### ISSUE THREAD

**Issue by mwittig** [Bastl34/node-yeelight-wifi#2]
First of thank you very for your effort in make this project available. I am using it since a couple of days now and it is working fine for me. However, I have an issue with respect to status update events.

The `stateUpdate` event only provides the Yeelight object with all its members, but it does not indicate which property has changed which can have some strange side-effect with some applications which represent the actual state of light.   In particular, this is a problematic on first connect as the state is incomplete at this point as can be seen in the following example:
```
{ type: 'unknown',
  power: false,
  bright: 0,
  rgb: { r: 0, g: 0, b: 0 },
  hsb: { h: 0, s: 0, b: 0 } }
{ type: 'color',
  power: true,
  bright: 0,
  rgb: { r: 0, g: 0, b: 0 },
  hsb: { h: 0, s: 0, b: 0 } }
{ type: 'color',
  power: true,
  bright: 100,
  rgb: { r: 255, g: 255, b: 255 },
  hsb: { h: 0, s: 0, b: 100 } }
```

As one can see the first two states are incomplete

My question: Is it possible to suppress the first events (the first one might be easy for me to ignore as the type is `unknown`) until the bulb state is complete? Another approach might be to have status update event which contain the actual state property changed rather than the full object. 

What do you think? I am happy to come up with PR based on your thoughts on the matter.

**Comment by mwittig** [comment]
I've just noticed there is an undocumented `update` event which contains the JSON object parsed from the response. So, that may do what I need ...

**Comment by Bastl34** [comment]
Hi

This sounds weird. 
I do currently not have the time to debug this. But feel free to fix this within a PR.
