### ISSUE TITLE
search/discovery timeout?

### ISSUE THREAD

**Issue by slametps** [Bastl34/node-yeelight-wifi#4]
Is it possible to have a discovery timeout after a period of time? Currently, it is a forever loop.

**Comment by Bastl34** [comment]
the `Lookup` is based on an interval.
You can do something like this to end the interval:

```
let look = new Lookup();

look.on("detected",(light) =>
{
    console.log("new yeelight detected: id="+light.id + " name="+light.name);

    //***HERE*** clear interval
    clearInterval(look.interval);
});
```

**Comment by slametps** [comment]
It is not working. The app is still running.

**Comment by Bastl34** [comment]
You can always use `process.exit()`...
