### ISSUE TITLE
Yeelight bulb not dtecteed

### ISSUE THREAD

**Issue by ni011901** [Bastl34/node-yeelight-wifi#6]
I have powered on the bulb and started the discovery code, bulb not detected
Any other thing to add up?

code I tried

const Lookup = require("node-yeelight-wifi").Lookup;

let look = new Lookup();

look.on("detected",(light) =>
{
    console.log("new yeelight detected: id="+light.id + " name="+light.name);
});

**Comment by Bastl34** [comment]
Hm. It looks correct. Have you tried the standard things? on/off, check your wifi and stuff?

**Comment by Bastl34** [comment]
@ni011901: any update on this? If your problem is gone I will then close the issue.
