### ISSUE TITLE
Allow use of async / await

### ISSUE THREAD

**Issue by igorclaudino** [Bastl34/node-yeelight-wifi#8]
Hello. I think with the new ES5 / 6 updates, it would be interesting to use async / await. What do you think? I can work in a PR for this.

**Comment by Bastl34** [comment]
You can use the current promise based methods with async/await ;)

**Comment by igorclaudino** [comment]
> You can use the current promise based methods with async/await ;)

Yeah, I realized that after I had already opened the issue. I'm sorry.

**Comment by igorclaudino** [comment]
And sorry about my english too. I am Brazilian. I'm training.
