### ISSUE TITLE
Allow sendCommand with empty params

### ISSUE THREAD

**Issue by tomschinelli** [Bastl34/node-yeelight-wifi#9]
Some of the api methods aren' t implemented.

Since it is possible to call the sendCommand function, it would be nice, if you can call the function without params.

In order to keep the stability, the parameters could be checked in the implemented function and not in the sendCommand function.
For instance the setRGB method requires prameters. Therefore setRGB should verify the parameters and pass them to the setCommand function.

This would allow to use api functionality that isn' t implemented in this module. e.g. "toggle"

Another option would be to explicitly tell the sendCommand function, that you want to call it without parameters.
e.g.:
 ```
setCommand('toggle', {
   params: [],
   allowEmptyParams: true
})
```

But this would be a breaking change.

**Comment by Bastl34** [comment]
Hi
Feel free to create a pull request for this feature.

**Comment by Bastl34** [comment]
closing it because of inactivity
